Update schedule.yml

diff --git a/.github/workflows/schedule.yml b/.github/workflows/schedule.yml
--- a/.github/workflows/schedule.yml
+++ b/.github/workflows/schedule.yml
@@ -40,16 +40,13 @@ jobs:
         env:
           GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/faith_bq_key.json
 
+      - name: Validate JSON format
+        run: |
+          echo "Validating JSON format..."
+          cat $GOOGLE_APPLICATION_CREDENTIALS | jq . || echo "Invalid JSON!"
+        env:
+          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/faith_bq_key.json
 
 
 
-      # - name: Set Weather API key
-      #   env:
-      #     WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
-      #   run: echo "$WEATHER_API_KEY" > weather_api_key.txt
 
-      # - name: Run Python script
-      #   env:
-      #     GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/faith_bq_key.json
-      #     WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
-      #   run: python weather_query.py
